version: '3.9'
services:
    app:
        build:
            context: .
        ports:
            - 8000:8000
        volumes:
            - ./app:/Django_Portfolio
        environment:
            - SECRET_KEY=b_lj(cc)n2(_824bak(qm++c565^6g*4)70i_h5y004x&2p_n%
            - DEBUG = TRUE
            - DB_HOST=db
            - DB_NAME=dev_db
            - DB_USER=devric
            - DB_PASS=devpass
        depends_on:
            - db
    db:
        image: postgres:13-alpine
        environment:
            - POSTGRES_DB=dev_db
            - POSTGRES_USER=devric
            - POSTGRES_PASSWORD=devpass
        
            