# Generated by Django 3.1.8 on 2021-12-20 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_tool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='logo',
            field=models.ImageField(default='avatar.svg', null=True, upload_to=''),
        ),
    ]
