# Generated by Django 3.1.8 on 2021-12-25 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20211220_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='resume_pic',
            field=models.ImageField(default='avatar.svg', null=True, upload_to=''),
        ),
    ]
